### ISSUE TITLE
NameError: name 'anchor_resolution' is not defined

### ISSUE THREAD

**Issue by tralala87** [MCG-NKU/AMT#1]
Getting this error when running last cell in colab:

`#@title # 3. Enjoy the Smooth Video
import PIL.Image
if not hasattr(PIL.Image, 'Resampling'):  # Pillow < 9.0
  PIL.Image.Resampling = PIL.Image
model_type_upper = model_type.upper()
!python3 '/content/AMT/demos/demo_2x.py' \
   --config cfgs/{model_type_upper}.yaml \
   --ckpt pretrained/{model_type}.pth \
   --out_path {outputs_dir} \
   --frame_rate {output_video_fps}  
from mediapy import read_video, show_video
video = read_video(f'{outputs_dir}/demo.avi')
show_video(video, fps=output_video_fps)`

I alo had to change the name of the python file to run, to demo_2x.py, the once originally written is I believe a typo.

**Comment by Paper99** [comment]
Thank you for pointing out it. We will fix ASAP.

**Comment by tralala87** [comment]
Also, 

`   --iters {recursive_interpolation_passes} \
   --dir {inputs_dir} \`

don't seem to be arguments in demo_2x.py

**Comment by NK-CS-ZZL** [comment]
We've fixed this bug. Remember to reboot the container before you rerun the code. Otherwise, the new code won't be cloned from GitHub (Alternatively, you can also remove `if osp.exists(f'AMT') is False:` to get new code.)
