### ISSUE TITLE
error

### ISSUE THREAD

**Issue by demirklvc** [MCG-NKU/AMT#2]
rm: cannot remove 'results': No such file or directory
Loading [images] from [['assets/quick_demo/a.JPG', 'assets/quick_demo/b.JPG']], the number of images = [2]
Traceback (most recent call last):
  File "/content/AMT/demos/demo_2x.py", line 104, in <module>
    inputs = [img2tensor(read(img_path)).to(device) for img_path in input_path]
  File "/content/AMT/demos/demo_2x.py", line 104, in <listcomp>
    inputs = [img2tensor(read(img_path)).to(device) for img_path in input_path]
  File "/content/AMT/./utils/utils.py", line 106, in read
    else: raise Exception('don\'t know how to read %s' % file)
Exception: don't know how to read assets/quick_demo/a.JPG
   1132   if not pathlib.Path(path).is_file():
-> 1133     raise RuntimeError(f"Video file '{path}' is not found.")
   1134   command = [
   1135       _get_ffmpeg_path(),

RuntimeError: Video file 'results/demo_0000.mp4' is not found.

**Comment by NK-CS-ZZL** [comment]
We've fixed it.
