### ISSUE TITLE
The training time cost

### ISSUE THREAD

**Issue by Amazingren** [MCG-NKU/AMT#7]
Very nice work!

May I know how long it costs to train the proposed method on the Vimeo dataset?
For example, with two 3090 gpus.

Bests and many thanks

**Comment by NK-CS-ZZL** [comment]
About 2 days for the small and medium model (amt-s, amt-l) and about 5 days for the large (amt-g).

**Comment by Amazingren** [comment]
> About 2 days for the small and medium model (amt-s, amt-l) and about 5 days for the large (amt-g).

thanks a lot!
