### ISSUE TITLE
Question about arbitrary time model

### ISSUE THREAD

**Issue by zzh-tech** [MCG-NKU/AMT#8]
Why not train an arbitrary time model on the Septuple set of Vimeo90K, which is larger than GOPRO?
I did some tests and the arbitrary time model trained on GOPRO does not perform well.

**Comment by Paper99** [comment]
We previously attempted to train on Septuplet but did not achieve good results.

**Comment by zzh-tech** [comment]
Thanks for your quick response :-)
Do you think it is necessary to train an arbitrary time model?
Assuming it can be trained well, what are the advantages over the fixed time model?

**Comment by Paper99** [comment]
If everything goes well, the frame interpolation results of an arbitrary time model at different timestep, except 1/2, will be better than calling a fixed time model recursively.

**Comment by zzh-tech** [comment]
So the theoretical advantages of arbitrary time model might be two points?
1. No accumulated errors result in better performance at different timestep except 1/2
2. Convenient/faster inference for specific timestep without iterations

**Comment by Paper99** [comment]
Sure, it is! 👍
